In [1]:
import pandas as pd
import pickle
from pandas_profiling import ProfileReport

pd.set_option('display.max_columns', 500)

We scraped Minnesota Department of Revenue and got a dataset with the house address and the price it was sold for. 
We use the address and scrap the historical zillow listing for the attribtues of the house.

### Data Source

* Minnesota Department of Revenue (https://www.revenue.state.mn.us/minnesota-department-revenue)

* Zillow (Zillow.com)

In [12]:
df = pd.read_csv("datafiles/data.csv")
df.drop(["Unnamed: 0", "index"], axis=1, inplace=True)
df.head(1)

,totPurchaseAmt,street1,zip,property,ZillowURL,zpid,streetAddress,zipcode,city,state,latitude,longitude,dateSold,bathrooms,bedrooms,livingArea,yearBuilt,lotSize,homeType,homeStatus,photoCount,imageLink,daysOnZillow,isFeatured,shouldHighlight,brokerId,zestimate,rentZestimate,listing_sub_type,priceReduction,isUnmappable,rentalPetsFlags,mediumImageLink,isPreforeclosureAuction,homeStatusForHDP,festimate,isListingOwnedByCurrentSignedInAgent,isListingClaimedByCurrentSignedInUser,hiResImageLink,watchImageLink,tvImageLink,tvCollectionImageLink,tvHighResImageLink,zillowHasRightsToImages,desktopWebHdpImageLink,isNonOwnerOccupied,hideZestimate,isPremierBuilder,isZillowOwned,currency,country,taxAssessedValue,streetAddressOnly,unit,averageSchoolRating,description,price,priceForHDP,hoaFee,contactPhone,status
0,152000.0,538 78th Avenue NE,55432.0,538 78th Avenue NE 55432,https://www.zillow.com/homedetails/538-78th-Av...,1475959,538 78th Ave NE,55432,Spring Lake Park,MN,45.108779,-93.257808,1569308400000,1.0,2.0,1300.0,1984,1225,CONDO,RECENTLY_SOLD,4,https://photos.zillowstatic.com/p_g/IS1fwt0hhf...,174,False,False,0,158110.0,1150.0,NaN,NaN,False,64.0,https://photos.zillowstatic.com/p_c/IS1fwt0hhf...,False,RECENTLY_SOLD,158110.0,False,False,https://photos.zillowstatic.com/p_f/IS1fwt0hhf...,https://photos.zillowstatic.com/p_j/IS1fwt0hhf...,https://photos.zillowstatic.com/p_m/IS1fwt0hhf...,https://photos.zillowstatic.com/p_l/IS1fwt0hhf...,https://photos.zillowstatic.com/p_n/IS1fwt0hhf...,True,https://photos.zillowstatic.com/p_h/IS1fwt0hhf...,NaN,False,False,False,USD,USA,-1.0,538 78th Ave NE,,4.0,"Just move in! End unit, deck, double garage, w...",152000.0,152000.0,230.0,NaN,Completed

In [13]:
df.columns

Index(['totPurchaseAmt', 'street1', 'zip', 'property', 'ZillowURL', 'zpid',
       'streetAddress', 'zipcode', 'city', 'state', 'latitude', 'longitude',
       'dateSold', 'bathrooms', 'bedrooms', 'livingArea', 'yearBuilt',
       'lotSize', 'homeType', 'homeStatus', 'photoCount', 'imageLink',
       'daysOnZillow', 'isFeatured', 'shouldHighlight', 'brokerId',
       'zestimate', 'rentZestimate', 'listing_sub_type', 'priceReduction',
       'isUnmappable', 'rentalPetsFlags', 'mediumImageLink',
       'isPreforeclosureAuction', 'homeStatusForHDP', 'festimate',
       'isListingOwnedByCurrentSignedInAgent',
       'isListingClaimedByCurrentSignedInUser', 'hiResImageLink',
       'watchImageLink', 'tvImageLink', 'tvCollectionImageLink',
       'tvHighResImageLink', 'zillowHasRightsToImages',
       'desktopWebHdpImageLink', 'isNonOwnerOccupied', 'hideZestimate',
       'isPremierBuilder', 'isZillowOwned', 'currency', 'country',
       'taxAssessedValue', 'streetAddressOnly', 'unit', 'averageSchoolRating',
       'description', 'price', 'priceForHDP', 'hoaFee', 'contactPhone',
       'status'],
      dtype='object')

### Selecting Features from Raw Data

https://berkshirehathawayhs.tomieraines.com/Blog/ID/272/13-Factors-That-Determine-Your-Home-Appraisal-Value

In [4]:
data = df[["totPurchaseAmt", 
           "latitude", 
           "longitude", 
           "bathrooms", 
           "ZillowURL", 
           "photoCount",
           "bedrooms",
           "livingArea",
           "yearBuilt", 
           "lotSize", 
           "averageSchoolRating",
           "zip",
           "description",
           "state",
           "homeType",
           "zestimate"
          ]]

In [5]:
len(data)

36408

### Filtering and Cleaning the Data

In [6]:
df.groupby('homeType').count()

,totPurchaseAmt,street1,zip,property,ZillowURL,zpid,streetAddress,zipcode,city,state,latitude,longitude,dateSold,bathrooms,bedrooms,livingArea,yearBuilt,lotSize,homeStatus,photoCount,imageLink,daysOnZillow,isFeatured,shouldHighlight,brokerId,zestimate,rentZestimate,listing_sub_type,priceReduction,isUnmappable,rentalPetsFlags,mediumImageLink,isPreforeclosureAuction,homeStatusForHDP,festimate,isListingOwnedByCurrentSignedInAgent,isListingClaimedByCurrentSignedInUser,hiResImageLink,watchImageLink,tvImageLink,tvCollectionImageLink,tvHighResImageLink,zillowHasRightsToImages,desktopWebHdpImageLink,isNonOwnerOccupied,hideZestimate,isPremierBuilder,isZillowOwned,currency,country,taxAssessedValue,streetAddressOnly,unit,averageSchoolRating,description,price,priceForHDP,hoaFee,contactPhone,status
homeType,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
APARTMENT,98,98,98,98,98,98,98,98,98,98,98,98,98,94,96,92,98,98,98,98,98,98,98,98,98,3,92,0,0,98,89,98,98,98,3,98,98,98,98,98,98,98,98,98,79,98,98,98,98,98,94,98,98,98,98,59,59,16,7,98
CONDO,570,570,570,570,570,570,570,570,570,570,570,570,570,561,564,562,570,570,570,570,570,570,570,570,570,564,566,0,3,570,491,570,570,570,564,570,570,570,570,570,570,570,570,570,337,570,570,570,570,570,569,570,570,570,570,565,565,499,16,570
HOME_TYPE_UNKNOWN,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,0,1,0,0,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1
LOT,114,114,114,114,114,114,114,114,114,114,114,114,114,9,90,74,114,114,114,114,114,114,114,114,114,0,86,0,0,114,66,114,114,114,0,114,114,114,114,114,114,114,114,114,50,114,114,114,114,114,111,114,114,114,114,85,85,11,7,114
MANUFACTURED,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0,0,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,5,7,7,7,7,7,7,7,7,7,7,7,7,1,0,7
MULTI_FAMILY,590,590,590,590,590,590,590,590,590,590,590,590,590,472,589,589,590,590,590,590,590,590,590,590,590,580,580,0,1,590,484,590,590,590,580,590,590,590,590,590,590,590,590,590,305,590,590,590,590,590,589,590,590,590,588,586,586,57,7,590
SINGLE_FAMILY,32675,32675,32675,32675,32675,32675,32675,32675,32675,32675,32675,32675,32675,32343,32553,32415,32675,32675,32675,32675,32675,32675,32675,32675,32675,32133,32046,0,87,32675,31459,32675,32675,32675,32133,32675,32675,32675,32675,32675,32675,32675,32675,32675,22132,32675,32675,32675,32675,32675,32638,32675,32675,32675,32632,32490,32490,4462,552,32675
TOWNHOUSE,2353,2353,2353,2353,2353,2353,2353,2353,2353,2353,2353,2353,2353,2350,2352,2350,2353,2353,2353,2353,2353,2353,2353,2353,2353,2333,2298,0,5,2353,2214,2353,2353,2353,2333,2353,2353,2353,2353,2353,2353,2353,2353,2353,1592,2353,2353,2353,2353,2353,2344,2353,2353,2353,2349,2350,2350,2022,64,2353

In [7]:
profile = ProfileReport(data, title="Pandas Profiling Report", explorative=False)
profile.to_widgets()

C:\anaconda\envs\py36\lib\site-packages\pandas\core\frame.py:4304: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

HBox(children=(HTML(value='Summarize dataset'), FloatProgress(value=0.0, max=30.0), HTML(value='')))

HBox(children=(HTML(value='Generate report structure'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Render widgets'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

In [8]:
data = data.dropna()

# Remove Duplicate House Listings
data = data.drop_duplicates(subset=['ZillowURL'], keep = 'first')

# We plan to just focus on SINGLE_FAMILY homes
data = data[data["homeType"] == "SINGLE_FAMILY"]
data = data.drop(columns=["homeType"])

# We filtered the pricing to be in a range of $50K to $5 Mil
data = data[data["totPurchaseAmt"] > 50000]
data = data[data["totPurchaseAmt"] < 5000000]

# We filter the bathroom count to be between 0.5 and 16
data = data[data["bathrooms"] >= 0.5]
data = data[data["bathrooms"] <= 16]

# We filter the bedroom count to be between 0 and 16
data = data[data["bedrooms"] >= 0]   # Studio Apartment
data = data[data["bedrooms"] <= 16]

# We filter the livingArea to be between 500 sqft and 10,000 sqft
# Total interior livable area
data = data[data["livingArea"] >= 1000] 
data = data[data["livingArea"] <= 30000]

# Filtering Year built
df = df[df["yearBuilt"] <= 2020]
df = df[df["yearBuilt"] >= 1940]

# Filtering ZipCode to be just from Minnesota
data = data[data["zip"] >= 55001]
data = data[data["zip"] <= 56763] 

# Filtering State to be just from Minnesota
data = data[data["state"] == "MN"] 

# Dropping attributes which would not help in the regression model
data = data.drop(columns=["state", "ZillowURL", "lotSize"])

# Converting Zip into a categorical variable
data["zip"] = data["zip"].apply(lambda x: str(int(x)))

In [9]:
data.head()

,totPurchaseAmt,latitude,longitude,bathrooms,photoCount,bedrooms,livingArea,yearBuilt,averageSchoolRating,zip,description,zestimate
1,198000.0,45.237189,-93.409535,2.0,0,4.0,1716.0,1996,5.333333,55303,"14649 Iodine Ct NW, Ramsey, MN is a single fam...",285985.0
3,415000.0,45.278217,-93.407533,2.0,30,3.0,3108.0,1985,6.333333,55303,Stunning walk to Rum River and Creek running t...,431995.0
4,329900.0,45.143781,-93.021604,3.0,0,4.0,1814.0,2001,6.500000,55038,"2372 Tart Lake Rd, Lino Lakes, MN is a single ...",318162.0
5,262000.0,45.164166,-93.297836,2.0,36,3.0,2158.0,1985,4.666667,55043,"This large rambler is located on a beautiful, ...",272169.0
6,280000.0,45.283700,-93.332023,2.0,22,3.0,1993.0,1976,7.333333,55304,You won't want to miss out on this beautiful h...,290365.0

In [10]:
profile = ProfileReport(data, title="Pandas Profiling Report", explorative=False)
profile.to_widgets()

HBox(children=(HTML(value='Summarize dataset'), FloatProgress(value=0.0, max=27.0), HTML(value='')))

HBox(children=(HTML(value='Generate report structure'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Render widgets'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

In [11]:
pickle.dump(data, open("datafiles/cleandata.ft", "wb"))